server:
  port: 8081

spring:
  datasource:
    username: 'root'
    password: 1234abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eShopDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

